version: "3.8"

services:
    testapp:
        image: mobylab/idp-laborator4-testapp
        ports:
            - 8000:8000
            - 5000:5000
        depends_on:
            - rabbitmq
        networks:
            - monitoring
            - rmq

    prometheus:
        image: prom/prometheus
        volumes:
            - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - monitoring

    node_exporter:
        image: prom/node-exporter
        deploy:
            mode: global
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        ports:
            - 9100:9100
        networks:
            - monitoring

    cadvisor:
        image: gcr.io/cadvisor/cadvisor
        deploy:
            mode: global
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        ports:
            - 8080:8080
        networks:
            - monitoring

    grafana:
        image: grafana/grafana
        volumes:
            - grafana-volume:/var/lib/grafana
        ports:
            - 3000:3000
        depends_on:
            - loki
        deploy:
            placement:
                constraints: [node.role == manager]
    
    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - rmq
        hostname: rabbitmq

    worker:
        image: mobylab/idp-laborator4-worker
        depends_on:
            - rabbitmq
        networks:
            - rmq

volumes:
    grafana-volume:

networks:
    monitoring:
    rmq: