apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:10.4
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-config-map
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-storage
      persistentVolumeClaim:
        claimName: postgres-pvc