services:
    laborator2-api:
        image: mobylab/idp-laborator2-api
        environment:
            PGUSER: admin
            PGPASSWORD: admin
            PGDATABASE: books
            PGHOST: laborator2-db
            PGPORT: 5432
        deploy:
            replicas: 2
            placement:
                max_replicas_per_node: 1
            restart_policy:
                condition: on-failure
        ports:
            - "5555:80"
        networks:
            - laborator2-api-network
        depends_on:
            - laborator2-db

    laborator2-db:
        image: postgres:12
        environment:
            POSTGRES_DB: books
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        volumes:
            - laborator2-db-persistent-volume:/var/lib/postgresql/data
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        networks:
            - laborator2-api-network
            - laborator2-adminer-network

    laborator2-visualizer:
        image: dockersamples/visualizer:stable
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        ports:
            - 8081:8080
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - laborator2-adminer-network
        depends_on:
            - laborator2-db
                
volumes:
    laborator2-db-persistent-volume:

networks:
    laborator2-api-network:
    laborator2-adminer-network:
