version: '3.8'

services:
  laborator2-api:
    image: alexandraion22/idp-laborator2-api
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGDATABASE: books
      PGHOST: laborator2-db
      PGPORT: 5432
    ports:
      - "5555:80"
    networks:
      - lab-net
    deploy:
      replicas: 2

  laborator2-db:
    image: postgres:12
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - lab-net

  laborator2-visualizer:
    image: alexellis2/visualizer-arm:latest
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - lab-net

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - lab-net
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  lab-net:
    driver: overlay
    attachable: true

volumes:
  db-data: